#### DO NOT CHANGE ANY PROPERTY, UNLESS YOU KNOW WHAT YOU ARE DOING ####
cas.server.name=http://localhost:8081
cas.server.prefix=http://localhost:8081/cas

server.ssl.keyStore=file:/etc/cas/thekeystore
server.ssl.keyStorePassword=changeit
server.ssl.keyPassword=changeit

# logging.config= file:/etc/cas/config/log4j2.xml
logging.level.org.apereo.cas=DEBUG

cas.service-registry.json.location=file:///etc/cas/services

cas.authn.accept.users=

cas.authn.attribute-repository.json[0].location=file:///etc/cas/attribute-repository.json
cas.authn.attribute-repository.json[0].order=0

cas.authn.file.password-encoder.encoding-algorithm=
cas.authn.file.password-encoder.type=NONE
cas.authn.file.separator=::
cas.authn.file.filename=file:///etc/cas/users.txt

cas.server.tomcat.http[0].port=8080
cas.server.tomcat.http[0].protocol=org.apache.coyote.http11.Http11NioProtocol
cas.server.tomcat.http[0].enabled=true

cas.logout.follow-service-redirects=true

#################################################################
## Ciphers                                                     ##
## Only kept here for demo purposes, do not use in production! ##
## Let CAS generate on first run and                           ##
## save them on the implementation configuration               ##
#################################################################
cas.tgc.crypto.encryption.key=iGQLU-0FXbU4NowkV2hIg0zwjgWvOgaKLeLqXCIwUoE
cas.tgc.crypto.signing.key=bADirACZdGw1099sB8You-oQ-05QXtNurkSeQNvWUdnM4h_KIiTycOMMMsiZEirCasWtULpG7Yv2-hHivogNZw
cas.webflow.crypto.encryption.key=fMFqQae9pnWt63p-YDcrBg
cas.webflow.crypto.signing.key=YkVnRUFERnxkXRutfbcpFE1kQzIVq20q9zJmRrBJRrSeRbfemb9_5fmq-du2-U6g_PvwhjJR9wb6QeBSE6Enew
