version: "3.2"
services:
  dbptke:
    image: keeps/dbvtk:v3.0.0
    container_name: dbptk-enterprise
    networks:
      - zoonet
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - SOLR_ZOOKEEPER_HOSTS=solr:9983
      - CAS_ENABLED=true
      - CAS_INTERNAL_URL=http://cas:8080/cas
      - CAS_EXTERNAL_URL=http://localhost:8181/cas
      - DBVTK_INTERNAL_URL=http://dbptke:8080
      - DBVTK_EXTERNAL_URL=http://localhost:8080
      - DBPTKE_SHARED_FOLDER=/volumes/siards
    volumes:
      # configuration overrides
      - ./dbptke/config/dbvtk-viewer.properties:/dbvtk/config/dbvtk-viewer.properties:ro
      # map /volumes/siards to the desired folder
    depends_on:
      - solr
    entrypoint: java -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.war
  solr:
    image: solr:9
    container_name: solr
    networks:
      - zoonet
    ports:
      - 8983:8983
    command: -c # Use cloud mode
  cas:
    image: docker.io/library/cas:latest
    container_name: cas
    build:
      context: ./image/cas
    networks:
      - zoonet
    ports:
      - 8181:8080
    volumes:
      - ./thekeystore:/etc/cas/thekeystore
      - ./cas/attribute-repository.json:/etc/cas/attribute-repository.json
      - ./cas/users.txt:/etc/cas/users.txt
      - ./cas/services:/etc/cas/services
      - ./cas/cas.properties:/etc/cas/config/cas.properties
  swagger:
    image: docker.io/swaggerapi/swagger-ui:v5.13.0
    restart: on-failure
    networks:
      - zoonet
    ports:
      - "8081:8080"
    environment:
      - URL=http://localhost:8080/openapi.json
      - DOC_EXPANSION=none
      - VALIDATOR_URL=none

networks:
  zoonet:
